name: bitbust
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

#
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6 
  http: ^1.2.1
  shared_preferences:
  # camera_android: ^0.10.7
  firebase_core: ^2.11.0
  overlay_support: ^2.1.0
  get: ^4.6.5
  rxdart: ^0.27.7
  intl: ^0.19.0
  image_picker: ^0.8.4+2 
  top_snackbar_flutter: ^3.1.0
  path_provider: ^2.0.8
  introduction_screen: ^3.0.0
  pinput: 1.2.0
  pin_code_fields: ^8.0.1
  intl_phone_field: ^3.1.0
  local_auth: ^2.1.3
  firebase_messaging:
  flutter_local_notifications:
  app_settings: ^5.1.1
  permission_handler: ^11.3.0
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.png
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: Gilroy Black
      fonts:
        - asset: fonts/Gilroy-Black.ttf
    - family: Gilroy Light
      fonts:
        - asset: fonts/Gilroy-Light.ttf
    - family: Gilroy Heavy
      fonts:
        - asset: fonts/Gilroy-Heavy.ttf
    - family: Gilroy Medium
      fonts:
        - asset: fonts/Gilroy-Medium.ttf
    - family: Gilroy Bold
      fonts:
        - asset: fonts/Gilroy-Bold.otf
    - family: Gilroy ExtraBold
      fonts:
        - asset: fonts/Gilroy-ExtraBold.otf
   
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
