// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSBQT2--2u0962n-Un-zo86AF4dfrcl64',
    appId: '1:913993183002:web:5af418f410c739702946a3',
    messagingSenderId: '913993183002',
    projectId: 'pushnotification-53ab9',
    authDomain: 'pushnotification-53ab9.firebaseapp.com',
    storageBucket: 'pushnotification-53ab9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNzsScFBzdHbFM1zPtQytbNojTL0RXIl4',
    appId: '1:913993183002:android:002ff4f9f6c3aee12946a3',
    messagingSenderId: '913993183002',
    projectId: 'pushnotification-53ab9',
    storageBucket: 'pushnotification-53ab9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYXN4agR-5Qi9EmfXNzH-IvSBkThDqcxo',
    appId: '1:913993183002:ios:2279fd89ddff96332946a3',
    messagingSenderId: '913993183002',
    projectId: 'pushnotification-53ab9',
    storageBucket: 'pushnotification-53ab9.appspot.com',
    iosBundleId: 'com.example.bitbust',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYXN4agR-5Qi9EmfXNzH-IvSBkThDqcxo',
    appId: '1:913993183002:ios:2279fd89ddff96332946a3',
    messagingSenderId: '913993183002',
    projectId: 'pushnotification-53ab9',
    storageBucket: 'pushnotification-53ab9.appspot.com',
    iosBundleId: 'com.example.bitbust',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSBQT2--2u0962n-Un-zo86AF4dfrcl64',
    appId: '1:913993183002:web:021b1fec053ffcd12946a3',
    messagingSenderId: '913993183002',
    projectId: 'pushnotification-53ab9',
    authDomain: 'pushnotification-53ab9.firebaseapp.com',
    storageBucket: 'pushnotification-53ab9.appspot.com',
  );
}
